FROM node:22-alpine

WORKDIR /app

ARG NPM_REGISTRY=https://registry.npmjs.org
RUN npm config set registry $NPM_REGISTRY


COPY package*.json ./

RUN npm install


COPY . .

RUN npx tsc

EXPOSE 5137

CMD ["node", "dist/server.js"]
